I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 246, in script
    if a.getViewed :
  File "game/script.rpy", line 246, in <module>
    if a.getViewed :
NameError: name 'a' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 246, in script
    if a.getViewed :
  File "C:\Users\Chris\Downloads\renpy-6.99.6-sdk\renpy\ast.py", line 1612, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Chris\Downloads\renpy-6.99.6-sdk\renpy\python.py", line 1477, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Chris\Downloads\renpy-6.99.6-sdk\renpy\python.py", line 1472, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 246, in <module>
    if a.getViewed :
NameError: name 'a' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.99.6.739
Angelica Victorian Detective 0.2
