I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1338, in script
    if warnbeatrice == True:
  File "game/script.rpy", line 1338, in <module>
    if warnbeatrice == True:
NameError: name 'warnbeatrice' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1338, in script
    if warnbeatrice == True:
  File "/Applications/renpy-6.99.6-sdk/renpy/ast.py", line 1612, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-6.99.6-sdk/renpy/python.py", line 1477, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-6.99.6-sdk/renpy/python.py", line 1472, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1338, in <module>
    if warnbeatrice == True:
NameError: name 'warnbeatrice' is not defined

Darwin-14.5.0-x86_64-i386-64bit
Ren'Py 6.99.6.739
Angelica Victorian Detective 0.2
