I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 385, in script
    $ icon = [Icon("images/Notes_UI.png", (1719, 0)) ]
  File "game/script.rpy", line 385, in <module>
    $ icon = [Icon("images/Notes_UI.png", (1719, 0)) ]
TypeError: __init__() takes exactly 4 arguments (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 385, in script
    $ icon = [Icon("images/Notes_UI.png", (1719, 0)) ]
  File "C:\Program Files (x86)\Renpy\renpy\ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Renpy\renpy\python.py", line 1460, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 385, in <module>
    $ icon = [Icon("images/Notes_UI.png", (1719, 0)) ]
TypeError: __init__() takes exactly 4 arguments (3 given)

Windows-8-6.2.9200
Ren'Py 6.99.7.858
Angelica Victorian Detective 0.2
